/** @type {import('tailwindcss').Config} */
// Theme mirrors the Stitch "Pro Ice Analytics" design system for ChelCoach.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001d33",
        "error-container": "#93000a",
        tertiary: "#4ae176",
        "tertiary-container": "#00b452",
        "tertiary-fixed-dim": "#4ae176",
        primary: "#98cbff",
        "surface-container-high": "#23293c",
        "on-surface-variant": "#bec7d4",
        "surface-container": "#191f31",
        "surface-bright": "#33394c",
        "on-tertiary-fixed": "#002109",
        error: "#ffb4ab",
        "on-background": "#dce1fb",
        "on-primary-container": "#00375a",
        outline: "#88919d",
        "surface-dim": "#0c1324",
        background: "#0c1324",
        "secondary-container": "#3e495d",
        "outline-variant": "#3f4852",
        "primary-container": "#00a3ff",
        "on-error": "#690005",
        "inverse-on-surface": "#2a3043",
        "surface-variant": "#2e3447",
        "surface-container-lowest": "#070d1f",
        "surface-container-highest": "#2e3447",
        "on-primary-fixed-variant": "#004a77",
        "on-surface": "#dce1fb",
        "surface-tint": "#98cbff",
        "on-tertiary-container": "#003d17",
        "primary-fixed-dim": "#98cbff",
        "inverse-primary": "#00629d",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary": "#263143",
        "on-primary": "#003354",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-low": "#151b2d",
        "on-tertiary": "#003915",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#005321",
        secondary: "#bcc7de",
        "tertiary-fixed": "#6bff8f",
        "on-secondary-container": "#aeb9d0",
        "secondary-fixed": "#d8e3fb",
        "inverse-surface": "#dce1fb",
        surface: "#0c1324",
        "primary-fixed": "#cfe5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-xl": ["Oswald", "sans-serif"],
        "headline-lg": ["Oswald", "sans-serif"],
        "headline-lg-mobile": ["Oswald", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
